#!/usr/bin/env bash
#this script displays fizzbuzz on multiples of 3 and 5, fizz when the number is a multiple of 3, and buzz when a multiple of 5. If neither, just #
n=1
while [ $n -le 100 ]
	do 
		case $n in
			$n % 3 -eq 0)
			echo fizzbuzz
			;;

			$n % 3 -eq 0)
			
			echo fizz
			;;
		$n % 5 -eq 0)
		
			echo buzz
			;;
		*)
			echo $n
			;;
		esac
		n=$((n+1))
	done
