#!/usr/bin/env bash
#this script displays fizzbuzz on multiples of 3 and 5, fizz when the number is a multiple of 3, and buzz when a multiple of 5. If neither, just #
n=1
while [ $n -le 100 ]
	do 
		if [ $n % 3 -eq 0 ] && [ $((n % 5 -eq 0)) ] 
		then
			echo fizzbuzz
		elif [ $((n % 3 -eq 0)) ]
		then	
			echo fizz
		elif [ $((n % 5 -eq 0)) ]
		then
			echo buzz
		else
			echo $n
		fi
		n=$((n+1))
	done
