#!/usr/bin/env bash
#this script displays the contents of /etc/passwd using a while loop
story=$(cat /etc/passwd)
while IFS=: read -r "${story[@]}"
do
	echo "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"
done 
f1=$f1
f2=$f2
f3=$f3
f4=$f4
f5=$f5
f6=$f6
f7=$f7
