#!/usr/bin/env bash
#this while loop prints Best School on lines 1-8 and 10 but prints Hi on line 9
x=0
while [ $x -le 10 ]
do
	if [ $x -eq 9 ]
	
	then
		echo Hi
	        x=$((x+1))
	else
	echo Best School
	x=$((x+1))
        fi
done
