#!/usr/bin/env bash
#this script displays unlucky numbers from China,Italy, and Japan and displas Best School on all other lines from 1 to 20
x=1
while [ $x -le 20 ]
	do
		case $x in
			4)
			bad luck from China
			;;
			9)
			bad luck from Japan
			;;
			17)
			bad luck from Italy
			;;
			*)
		esac
		echo Best School 
		x=$((x+1))
	done
