#!/usr/bin/env bash
#this while loop creates a clock that runs for 12 hours and 59 minutes showing the hour and minute
h=0
m=1
while [ $h -le 12 ] 
	do 
		echo Hour: $h
	       while [ $m -le 59 ]
	       	do
	 		echo $m
		m=$((m+1))
		done
		h=$((h+1))		

		
	done

