#!/usr/bin/env bash
#this script does a lot of things
touch /var/run/myscript.pid

echo "#/usr/bin/env bash" > /var/run/myscript.pid
userID=$(ps /var/run/myscript.pid)
userID=$userID

trap "echo I hate the kill command; rm -r /var/run/myscript.pid; exit" 15
trap "echo Y U no love me?!; rm -r /var/run/myscript.pid; exit" 2


echo "$$" > /var/run/myscript.pid
while true 
do 
	echo "To infinity and beyond"
	
done
