#!/usr/bin/env bash
#Two seperate files?
m=manage_my_process
if [ "$1" = start ] 
then
 	
	start "$m"
	touch /var/run/my_process.pid
	echo $$ > /var/run/my_process.pid
	echo "$m started"



elif [ "$1" = stop ] 
then
 
	stop "$m"
	rm -r /var/run/my_process.pid
	echo "$m stopped"
 


elif [ "$1" = restart ] 
then

	stop "$m"
	rm -r /var/run/my_process.pid
	start $m
	touch /var/run/my_process.pid
	echo $$ > /var/run/my_process.pid
	echo "$m restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"

fi

jobs

